### ISSUE TITLE
change YouTube Links

### ISSUE THREAD

**Issue by PurpurTentakel97** [TechStreamConference/website-backend#30]
YouTube has a special embed link to embed Videos.
Other ways YouTube will reject the connection. 

There are two Options.
- 1
You provide a full Links that looks like this:
`https://youtube.com/embed/IW1vQAB6B18`

- 2
You only provide the Video ID and I build the link:
`IW1vQAB6B18`

Both valid solutions.
What ever is better for you.

**Comment by peddermaster2** [comment]
My 2 cents:
At work we accept all valid youtube urls and parse the id out and only save that and then use the correct embed urls with that id.

**Comment by PurpurTentakel97** [comment]
But that should do the backend before storing it into the database right?
Or should I do that in the frontend?
Just redundant for fast feedback I think.

**Comment by mgerhold** [comment]
I guess it would be best if the backend would store only the ID. To avoid misuse of the API, the backend should do the parsing, I guess. The frontend *can* also do the parsing, but only for user feedback.
When the backend returns an ID to the frontend, it should only be the ID, not a link. The backend cannot know whether you want to create a link to the video or embed it.
