### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by PurpurTentakel97** [TechStreamConference/website-backend#31]
When I display start and end date at the frontpage it looks like this: `2024-06-22 - 2024-06-23`
Is there a way you can format that in a non  American style?
Something like: `22.06.2024 - 23.06.2024`

**Comment by peddermaster2** [comment]
The api should always provide the dates / datetimes in [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339) or [ISO 8601](https://de.wikipedia.org/wiki/ISO_8601) format.
The frontend should display it in an appropiate format to the users.

**Comment by mgerhold** [comment]
I agree to what @peddermaster2 said. The backend should not be responsible for formatting. If you also agree, please close this issue as "not planned".
