### ISSUE TITLE
Fix year in default route

### ISSUE THREAD

**Issue by PurpurTentakel97** [TechStreamConference/website-backend#51]
When I call this endpoint the provided year inside the event is undefined.
`$routes->get('events', [Event::class, 'get']);`
When I call an explicit year the endpoint seems to return my provided year.
`$routes->get('events/(:num)', [Event::class, 'get']);`

It seams that this code is the issue. 
https://github.com/TechStreamConference/website-backend/blob/main/app/Controllers/Event.php#L19-L23
As long as I don't provide a year the year variable stays uninitialized.

Im fine with two options. (or provide an other option if you have one)
1.  You provide a year when this is zero
2.  I parse the year from one of the dates. 

As far is I know I need this to generate a title text for the YouTube video and the ICS Link
The Event title what so ever has the year already in it.

**Comment by mgerhold** [comment]
Good finding! And thanks for already pointing out the part of the code that causes the issue. That made fixing it really easy!

In my solution, I will just take care of the value being initialized in *all* cases now. That's how it should behave, I think. And in the frontend, you don't need any additional logic then. I'll open the PR right away... :)
