### ISSUE TITLE
route request for events dashboard

### ISSUE THREAD

**Issue by PurpurTentakel97** [TechStreamConference/website-backend#55]
- /dashboard/admin/all-events (returns a list of years of all existing events)
- /dashboard/admin/event/{:num} (returns all data of the provided year. Can this route also save data?)
- /dashboard/admin/event/new (generates a new event. Should there be all Values already be provided or not?)

Does this makes sense to you?

**Comment by mgerhold** [comment]
Regarding the second endpoint (`/dashboard/admin/event/{:num}`), should `num` really be the year or should it rather be the id? Using the year would break things if we have multiple events per year.

Regarding your question about the creation of new events: Yes, you'd have to provide all the necessary data upon creation.

**Comment by PurpurTentakel97** [comment]
The hole webside will not work anymore when we have to events in a year because I request the old events by year right?
I general im fine with using ids. :)

**Comment by mgerhold** [comment]
I don't know what will break in such a case. But yes, I also think that *a lot* would break 😂 We can test that someday 😅
