### ISSUE TITLE
internal sever error | key not existing

### ISSUE THREAD

**Issue by PurpurTentakel97** [TechStreamConference/website-backend#77]
When I Post Request this endpoint `$routes->post('dashboard/speaker/event/(:num)', [SpeakerDashboard::class, 'createOrUpdate'], ['filter' => SpeakerAuthFilter::class]);` a internal server error occurred.

After some debugging I can say the code fails right here: https://github.com/TechStreamConference/website-backend/blob/74-provide-necessary-endpoints-for-the-speaker-dashboard/app/Controllers/ContributorDashboard.php#L182-L191

More accurate: All index calls for `existingEntry` are broken because there is an array inside of an array.

I fixed this temporarily local like this:
```
    public function updateEntry(array $validData, array $existingEntry, int $eventId): ResponseInterface
    {
        // If there's an existing entry, we *still* want to create a new entry, but only with the fields
        // that are being updated. For the other fields, we copy the values from the existing entry.
        $uploadResult = $this->uploadPhoto();
        $hasPhoto = !($uploadResult instanceof ResponseInterface);
        $path = $hasPhoto ? $uploadResult[0] : null;
        $mimeType = $hasPhoto ? $uploadResult[1] : null;

        $newArray = reset($existingEntry); // <- "fix"

        $this->getModel()->create(
            name: $validData['name'] ?? $newArray['name'],
            userId: $this->getLoggedInUserId(),
            eventId: $eventId,
            shortBio: $validData['short_bio'] ?? $newArray['short_bio'],
            bio: $validData['bio'] ?? $newArray['bio'],
            photo: $hasPhoto ? $path : $newArray['photo'],
            photoMimeType: $hasPhoto ? $mimeType : $newArray['photo_mime_type'],
            isApproved: $newArray['is_approved'],
            visibleFrom: $newArray['visible_from'] ?? null,
        );
    
        return $this
            ->response
            ->setJSON(['message' => "Based new {$this->getRoleName()} entry on existing entry."])
            ->setStatusCode(201);
    }
```

Right now the first line that is broken is: `photo: $hasPhoto ? $path : $newArray['photo'],` because I provide the other fiels always. Should I provide null if there is no change in data or not?
I would have to track the data changes. Witch I currently don't so.

**Comment by mgerhold** [comment]
fixed
