### ISSUE TITLE
Buggy Speaker entries

### ISSUE THREAD

**Issue by PurpurTentakel97** [TechStreamConference/website-backend#78]
When I request a Speaker entry with this route: `https://github.com/TechStreamConference/website-backend/blob/74-provide-necessary-endpoints-for-the-speaker-dashboard/app/Config/Routes.php#L54` I don't get the new entry. Even when I saved the data successfully the returned data are still the same.
It seems that the save process is working just fine. The expected entries are in the database.

Also the displayed entries for the main page seems kind of broken because when I approve the data manually in the database the expected data gets not delivered.

**Comment by mgerhold** [comment]
This is not a bug, this is a feature 🫠
The error stems from the data that is produces by the seeders. That data contains `updated_at` values that are in the future.
